id: P007000
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9032
  title: བྱ་བ་ཀུན་ལས་བཏུས་པ།
  author: ''
  volumes:
    0330f1ffedcb4f43a7f18966fb03865c:
      image_group_id: I1KG9056
      title: ''
      volume_number: 1
      total_pages: 418
ebook_metadata:
  title: བྱ་བ་ཀུན་ལས་བཏུས་པ།
  author: ''
  sku: P007000
  cover: cover.jpg
  layers:
  - pagination
